<a href="https://colab.research.google.com/github/marcorvalanm/mly1101-machine-learning-portafolio/blob/main/1_1_2_Verificacion_Entorno_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Script de diagnóstico del entorno MLY1101
import sys
import numpy as np
import pandas as pd
import matplotlib
print("=== DIAGNÓSTICO DEL ENTORNO DE DESARROLLO ===")
print(f"Versión de Python instalada: {sys.version}")
print(f"Versión de NumPy: {np.__version__}")
print(f"Versión de Pandas: {pd.__version__}")
print(f"Versión de Matplotlib: {matplotlib.__version__}")
print("============================================")
print("¡Entorno verificado con éxito para análisis exploratorio!")

=== DIAGNÓSTICO DEL ENTORNO DE DESARROLLO ===
Versión de Python instalada: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Versión de NumPy: 2.0.2
Versión de Pandas: 2.2.2
Versión de Matplotlib: 3.10.0
============================================
¡Entorno verificado con éxito para análisis exploratorio!

In [2]:
#creacion de un arreglo e incremeto vectorial
pesos = np.array([75.5, 82.1, 90.4, 68.9])
pesos_ajustados = pesos * 1.05

print(pesos_ajustados)
# Output rápido y directo sin loops

[79.275 86.205 94.92  72.345]

In [4]:
pesos_ajustados.shape

(4,)

In [5]:
pesos_ajustados.ndim

1

In [6]:
pesos_ajustados.dtype

dtype('float64')

In [7]:
pesos_ajustados[0]

np.float64(79.275)

In [9]:
# Creación de una Serie con índice
ventas = pd.Series([450, 600, 320],
index=['Ene', 'Feb', 'Mar'])
ventas

Ene    450
Feb    600
Mar    320
dtype: int64

In [10]:
print(ventas['Feb'])
# Acceso directo por etiqueta

600

In [11]:
# Estructura típica de una matriz de datos
data = {
'edad': [23, 45, 31],
'compras': [120.5, 450.0, 85.2]
}
df = pd.DataFrame(data)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   edad     3 non-null      int64
 1   compras  3 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 180.0 bytes
None

In [45]:
df2=pd.read_csv('ecommerce_customer_data.csv')
df2.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [76]:
# Carga inicial controlando delimitadores y codificación estándar
df_clientes = pd.read_csv('ecommerce_customer_data.csv', sep=',',
encoding='utf-8')

In [77]:
# Inspección de las dimensiones de la matriz de datos
print(f"Dimensiones del dataset cargado: {df_clientes.shape}")

Dimensiones del dataset cargado: (10000, 14)

In [78]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [79]:
df_clientes.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [80]:
salario=np.array(df2['EstimatedSalary'])
salario_calculado=(salario*1.19) +2.5

In [81]:
salario_calculado

array([120607.6672, 133928.1702, 135581.0683, ...,  50084.3402,
       110539.8388,  45449.5282])

In [84]:
df_clientes['NetOperatingExpense'] = salario_calculado

df_clientes_segmento = df_clientes.iloc[50:101, [1, -1]]
display(df_clientes_segmento.head())

    CustomerId  NetOperatingExpense
50    15616550          235692.9004
51    15768193          102847.7383
52    15683553          139206.5461
53    15702298          195211.2186
54    15569590           47620.0644